backend:
  name: github
  repo: elisium/globiez-website

media_folder: static/assets
public_folder: assets

collections:
  - name: vacancies
    label: Vacancies
    folder: src/vacancies
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: tags, label: Labels }
      - { name: body, label: Body, widget: markdown }